name: CI
on:
  push:
    branches:
      - master
      - v2
  pull_request:
    branches:
      - master
      - v2
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: npm install --location=global gulp-cli
      - run: npm install
      - run: gulp lint
      - run: gulp coverage
      - name: Submit results to Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: test-python-${{ matrix.python-version }}
          parallel: true
  coveralls-finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
  deploy-docs:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: documentation
      url: https://docs.baby-buddy.net
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          REQUIREMENTS: docs/requirements.txt
#  deploy:
#    needs: test
#    runs-on: ubuntu-latest
#    environment:
#      name: demo
#      url: http://demo.baby-buddy.net
#    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Deploy demo
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
